version: '3.7'
services:
  mermaid:
    build:
      context: .
      target: mermaid-dev
      args:
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
        ALLOWED_EMAILS: ${ALLOWED_EMAILS}
    volumes:
      - ./src:/app/src
      - ./bin:/app/bin
      - ./vite.config.js:/app/vite.config.js
      - mermaid-diagrams:/app/data/diagrams
    ports:
      - 3000:3000
      - 24678:24678
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ALLOWED_EMAILS=${ALLOWED_EMAILS}

volumes:
  mermaid-diagrams:
